package com.rodrigoguerrero.myweather.ui.theme

import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF974811)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFFFFDBC9)
val lightOnPrimaryContainer = Color(0xFF331200)
val lightSecondary = Color(0xFF765848)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFFFDBC9)
val lightOnSecondaryContainer = Color(0xFF2B160A)
val lightTertiary = Color(0xFF636032)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFEAE5AB)
val lightOnTertiaryContainer = Color(0xFF1E1C00)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFFFFBFF)
val lightOnBackground = Color(0xFF201A17)
val lightSurface = Color(0xFFFFFBFF)
val lightOnSurface = Color(0xFF201A17)
val lightSurfaceVariant = Color(0xFFF4DED4)
val lightOnSurfaceVariant = Color(0xFF52443C)
val lightOutline = Color(0xFF85746B)
val lightInverseOnSurface = Color(0xFFFBEEE9)
val lightInverseSurface = Color(0xFF362F2C)
val lightInversePrimary = Color(0xFFFFB68E)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF974811)
val lightOutlineVariant = Color(0xFFD7C2B9)
val lightScrim = Color(0xFF000000)
