name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build android
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Write local.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo apiKey=$API_KEY >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: |
            androidApp/build/outputs/apk/debug/androidApp-debug.apk

  build_ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Write local.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo apiKey=$API_KEY >> local.properties

      - name: Build iOS app
        run: xcodebuild -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphonesimulator
